from enum import Enum

class PermissionTypes(Enum):
    
    ADMIN = "ADMIN"
    MEDIA = "MEDIA"
    CHATBOT = "CHATBOT"
    INTERACTIVE_CHAT = "INTERACTIVE_CHAT"
    AVATAR = "AVATAR"
    SPEECH = "SPEECH"
    CHAT_HISTORY = "CHAT_HISTORY"
    DOCUMENT_INTELLIGENCE = "DOCUMENT_INTELLIGENCE"
    SEARCH = "SEARCH"
    SOCIAL_MEDIA = "SOCIAL_MEDIA"
    FAQ = "FAQ"
    VIDEO_INDEXER = "VIDEO_INDEXER"